site_name: rran

repo_name: ranwiki
repo_url: https://github.com/111rran/ranwiki

nav:
  - Introduction: index.md
  - Semesters:
    - 2409 semester: semesters_intro/2409.md
    - 2502 semester: semesters_intro/2502.md
    - 2504 semester: semesters_intro/2504.md
    - 2509 semester: semesters_intro/2509.md
  - 2026美赛备赛资料:
    - 可视化: mcm2026/visualization.md
    - 优秀论文: mcm2026/papers.md

theme:
  name: 'material'
  features:
    - navigation.instant          # 即时加载页面
    - navigation.tabs             # 启用标签式导航
    - navigation.tabs.sticky      # 粘性标签导航
    - navigation.sections         # 启用分节导航
    - navigation.tracking         # URL 跟踪
    - navigation.footer           # 启用页脚导航
    - content.code.select         # 代码行选择按钮
    - content.code.copy           # 代码复制按钮
    - search.highlight            # 高亮搜索结果

  # 亮暗模式设置
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
  - mkdocstrings:
      handlers:
        python:
          paths: [src/user_manager]
          options:
            members_order: source
            docstring_style: google
            show_root_heading: true         # 为顶级对象生成标题
            show_symbol_type_heading: true  # 为不同类型doc生成类型标志(func,class,meth...)
            show_source: false              # 不显示源码链接
            separate_signature: True        # 将函数名与描述分开


markdown_extensions:
  # 代码块显示效果设置
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # 扩展语法
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # 公式支持
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2026 - 2025 lkkkkt
extra:
  generator: false